Pantalla de grabación provisoria
Ballena0/app-pi-gpi pull request #2
Opened 2021-06-20 02:17 UTC by mapacheverdugo

# Description

Arme la pantalla de grabación provisoria, lo que implicó agregar varias librerías como [dio](https://pub.dev/packages/dio) para las consultas HTTP, [flutter_sound](https://pub.dev/packages/flutter_sound) para la grabación y reproducción, [get](https://pub.dev/packages/get) para la navegación sin `context, [permission_handler](https://pub.dev/packages/permission_handler) para el manejo de permisos y [flutter_markdown](https://pub.dev/packages/flutter_markdown) para mostrar la respuesta del servidor.

La idea es que puedan grabar su audio con el botón, ingresar la URL de la API (puede ser IP local) y se enviará una consulta `POST` como `multipart` con el archivo en un parámetro llamado `audio` (que es como vi que lo maneja la @mariam6697)

La librería de audio permite parametrizar varias cosas como el formato, la frecuencia, el codec entre otras. Sería bueno que me digan cuál les gustaría dejar parametrizable, y cual fijo (y en qué valor).

![image](https://user-images.githubusercontent.com/16374322/122659927-b89cc900-d14a-11eb-9b7c-0d26c4048b99.png)

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change (cambio que puede romper la aplicación)
- [ ] Docs

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2021-06-20 22:44 UTC, Ballena0 approved these changes
Me gusta, esta weno. La ruta, como dices, puede ser `localhost:port` cierto?. Pregunta, ¿Solo lo puedo instalar en movil? ¿Existe alguna instrucción rápida de como instalar?

2021-06-21 01:33 UTC, mapacheverdugo commented
`localhost` como tal no creo que sea lo que buscas, porque haría referencia a tu teléfono.  Pero sí puede ser la IP local, `192.168.1.23` por ejemplo

No lo he probado en web, pero está habilitado por defecto, quizás falta alguna configuración adicional, si podi probarlo bacán uwu. Y el cómo correrlo está en el README autogenerado de Flutter. Ahora si quieres puedo subir la APK

2021-06-21 01:49 UTC, Ballena0 commented
> `localhost` como tal no creo que sea lo que buscas, porque haría referencia a tu teléfono. Pero sí puede ser la IP local, `192.168.1.23` por ejemplo
> 
> No lo he probado en web, pero está habilitado por defecto, quizás falta alguna configuración adicional, si podi probarlo bacán uwu. Y el cómo correrlo está en el README autogenerado de Flutter. Ahora si quieres puedo subir la APK

Lo que sea más sencillo la verdad, por ahora creo que está bien. Gracias

2021-06-21 01:52 UTC, mariam6697 requested changes
Dos cositas. En teoría, si tu PC y tu celu están en la misma red, desde el celu puedes hacer referencia al localhost del PC con `http://127.0.0.1:5000/`. Digo en teoría porque en otros casos no me ha dado problemas, pero ahora mismo no puedo verificar precisamente porque los cambios de esta PR no me corren (?).

Y eso es lo segundo: se me rompió la Miku. Es un unhandled exception al mandar el audio, me imagino que no debe ser difícil de arreglar. O puede ser que esté yo haciendo todo mal, quién sabe u.u

Adjunto stacktrace:

```
E/flutter (14360): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter (14360): #0      _RecordScreenState._sendAudio (package:miku/screens/record_screen.dart:77:29)
E/flutter (14360): <asynchronous suspension>
E/flutter (14360):
```

2021-06-22 02:24 UTC, mariam6697 approved these changes

2021-06-22 02:25 UTC, merged